import React from "react";
import PlaylistComponent from "components/playlist";
import Head from "next/head";
const PlayList = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico.png" />
        <title>Musica || Playlist</title>
      </Head>
      <PlaylistComponent />
    </>
  );
};

export default PlayList;
