import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Landing from "components/landing";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico.png" />
        <title>Musica</title>
      </Head>
      <Landing />
    </>
  );
};

export default Home;
