import React from "react";
import AlbumDetail from "components/details";
import Head from "next/head";
const AlbumContent = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico.png" />
        <title>Musica || Album</title>
      </Head>
      <AlbumDetail />
    </>
  );
};

export default AlbumContent;
